* Psalms 2
1. Why do the heathen rage, and the people imagine a vain thing? 
2. The kings of the earth set themselves, and the rulers take counsel together, against YHWH, and against his anointed, saying, 
3. Let us break their bands asunder, and cast away their cords from us. 
4. He that sitteth in the heavens shall laugh: YHWH shall have them in derision. 
5. Then shall he speak unto them in his wrath, and vex them in his sore displeasure. 
6. Yet have I set my king upon my holy hill of Zion. 
7. I will declare the decree: YHWH hath said unto me, Thou art my Son; this day have I begotten thee. 
8. Ask of me, and I shall give thee the heathen for thine inheritance, and the uttermost parts of the earth for thy possession. 
9. Thou shalt break them with a rod of iron; thou shalt dash them in pieces like a potter’s vessel. 
10. Be wise now therefore, O ye kings: be instructed, ye judges of the earth. 
11. Serve YHWH with fear, and rejoice with trembling. 
12. Kiss the Son, lest he be angry, and ye perish from the way, when his wrath is kindled but a little. Blessed are all they that put their trust in him. 
