* Psalms 30
1. A Psalm and Song at the dedication of the house of David. I will extol thee, O YHWH; for thou hast lifted me up, and hast not made my foes to rejoice over me. 
2. O YHWH my God, I cried unto thee, and thou hast healed me. 
3. O YHWH, thou hast brought up my soul from the grave: thou hast kept me alive, that I should not go down to the pit. 
4. Sing unto YHWH, O ye saints of his, and give thanks at the remembrance of his holiness. 
5. For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning. 
6. And in my prosperity I said, I shall never be moved. 
7. YHWH, by thy favour thou hast made my mountain to stand strong: thou didst hide thy face, and I was troubled. 
8. I cried to thee, O YHWH; and unto YHWH I made supplication. 
9. What profit is there in my blood, when I go down to the pit? Shall the dust praise thee? shall it declare thy truth? 
10. Hear, O YHWH, and have mercy upon me: YHWH, be thou my helper. 
11. Thou hast turned for me my mourning into dancing: thou hast put off my sackcloth, and girded me with gladness; 
12. To the end that my glory may sing praise to thee, and not be silent. O YHWH my God, I will give thanks unto thee for ever. 
