* Jeremiah 29
1. Now these are the words of the letter that Jeremiah the prophet sent from Jerusalem unto the residue of the elders which were carried away captives, and to the priests, and to the prophets, and to all the people whom Nebuchadnezzar had carried away captive from Jerusalem to Babylon; 
2. (After that Jeconiah the king, and the queen, and the eunuchs, the princes of Judah and Jerusalem, and the carpenters, and the smiths, were departed from Jerusalem;) 
3. By the hand of Elasah the son of Shaphan, and Gemariah the son of Hilkiah, (whom Zedekiah king of Judah sent unto Babylon to Nebuchadnezzar king of Babylon) saying, 
4. Thus saith YHWH of hosts, the God of Israel, unto all that are carried away captives, whom I have caused to be carried away from Jerusalem unto Babylon; 
5. Build ye houses, and dwell in them; and plant gardens, and eat the fruit of them; 
6. Take ye wives, and beget sons and daughters; and take wives for your sons, and give your daughters to husbands, that they may bear sons and daughters; that ye may be increased there, and not diminished. 
7. And seek the peace of the city whither I have caused you to be carried away captives, and pray unto YHWH for it: for in the peace thereof shall ye have peace. 
8. ¶ For thus saith YHWH of hosts, the God of Israel; Let not your prophets and your diviners, that be in the midst of you, deceive you, neither hearken to your dreams which ye cause to be dreamed. 
9. For they prophesy falsely unto you in my name: I have not sent them, saith YHWH. 
10. ¶ For thus saith YHWH, That after seventy years be accomplished at Babylon I will visit you, and perform my good word toward you, in causing you to return to this place. 
11. For I know the thoughts that I think toward you, saith YHWH, thoughts of peace, and not of evil, to give you an expected end. 
12. Then shall ye call upon me, and ye shall go and pray unto me, and I will hearken unto you. 
13. And ye shall seek me, and find me, when ye shall search for me with all your heart. 
14. And I will be found of you, saith YHWH: and I will turn away your captivity, and I will gather you from all the nations, and from all the places whither I have driven you, saith YHWH; and I will bring you again into the place whence I caused you to be carried away captive. 
15. ¶ Because ye have said, YHWH hath raised us up prophets in Babylon; 
16. Know that thus saith YHWH of the king that sitteth upon the throne of David, and of all the people that dwelleth in this city, and of your brethren that are not gone forth with you into captivity; 
17. Thus saith YHWH of hosts; Behold, I will send upon them the sword, the famine, and the pestilence, and will make them like vile figs, that cannot be eaten, they are so evil. 
18. And I will persecute them with the sword, with the famine, and with the pestilence, and will deliver them to be removed to all the kingdoms of the earth, to be a curse, and an astonishment, and an hissing, and a reproach, among all the nations whither I have driven them: 
19. Because they have not hearkened to my words, saith YHWH, which I sent unto them by my servants the prophets, rising up early and sending them; but ye would not hear, saith YHWH. 
20. ¶ Hear ye therefore the word of YHWH, all ye of the captivity, whom I have sent from Jerusalem to Babylon: 
21. Thus saith YHWH of hosts, the God of Israel, of Ahab the son of Kolaiah, and of Zedekiah the son of Maaseiah, which prophesy a lie unto you in my name; Behold, I will deliver them into the hand of Nebuchadrezzar king of Babylon; and he shall slay them before your eyes; 
22. And of them shall be taken up a curse by all the captivity of Judah which are in Babylon, saying, YHWH make thee like Zedekiah and like Ahab, whom the king of Babylon roasted in the fire; 
23. Because they have committed villany in Israel, and have committed adultery with their neighbours’ wives, and have spoken lying words in my name, which I have not commanded them; even I know, and am a witness, saith YHWH. 
24. ¶ Thus shalt thou also speak to Shemaiah the Nehelamite, saying, 
25. Thus speaketh YHWH of hosts, the God of Israel, saying, Because thou hast sent letters in thy name unto all the people that are at Jerusalem, and to Zephaniah the son of Maaseiah the priest, and to all the priests, saying, 
26. YHWH hath made thee priest in the stead of Jehoiada the priest, that ye should be officers in the house of YHWH, for every man that is mad, and maketh himself a prophet, that thou shouldest put him in prison, and in the stocks. 
27. Now therefore why hast thou not reproved Jeremiah of Anathoth, which maketh himself a prophet to you? 
28. For therefore he sent unto us in Babylon, saying, This captivity is long: build ye houses, and dwell in them; and plant gardens, and eat the fruit of them. 
29. And Zephaniah the priest read this letter in the ears of Jeremiah the prophet. 
30. ¶ Then came the word of YHWH unto Jeremiah, saying, 
31. Send to all them of the captivity, saying, Thus saith YHWH concerning Shemaiah the Nehelamite; Because that Shemaiah hath prophesied unto you, and I sent him not, and he caused you to trust in a lie: 
32. Therefore thus saith YHWH; Behold, I will punish Shemaiah the Nehelamite, and his seed: he shall not have a man to dwell among this people; neither shall he behold the good that I will do for my people, saith YHWH; because he hath taught rebellion against YHWH. 
