
* The First Book of Moses, Commonly Called Genesis 1
1. In the beginning, God created the heavens and the earth.
2. The earth was formless and empty. Darkness was on the surface of the deep and God’s Spirit was hovering over the surface of the waters[fn:1].
3. God said, “Let there be light,” and there was light.
4. God saw the light, and saw that it was good[fn:2]. God divided the light from the darkness[fn:3].
5. God called the light “day”, and the darkness he called “night”. There was evening and there was morning, the first day.
6. God said, “Let there be an expanse in the middle of the waters, and let it divide the waters from the waters.”  
7. God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.
8. God called the expanse “sky”. There was evening and there was morning, a second day.
9. God said, “Let the waters under the sky be gathered together to one place, and let the dry land appear”; and it was so.  
10. God called the dry land “earth”, and the gathering together of the waters he called “seas”. God saw that it was good.  
11. God said, “Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth”; and it was so.  
12. The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good.
13. There was evening and there was morning, a third day.
14. God said, “Let there be lights in the expanse of sky to divide the day from the night; and let them be for signs to mark seasons, days, and years; and let them be for lights in the expanse of sky to give light on the earth”; and it was so.  
15. God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.  
16. God set them in the expanse of sky to give light to the earth,  
17. and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.
18. There was evening and there was morning, a fourth day.
19. God said, “Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of sky.”
20. God created the large sea creatures and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.  
21. God blessed them, saying, “Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth.”  
22. There was evening and there was morning, a fifth day.    
23. God said, “Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind”; and it was so.  
24. God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.    
25. God said, “Let us make man[fn:4] in our[fn:5] image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth.”
26. God created man in his own image. In God’s image he created him; male and female he created them.
27. God blessed them. God said to them, “Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth.”
28. God said, “Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food.
29. To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;” and it was so.
30. God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.

* Footnotes

[fn:1] See §201909300955

[fn:2] Creation was good. Matter was good. The phyisical realm is not bad, but good

[fn:3] God's creative act is division. Categories.

[fn:4] Man is both male and female. Even Man has two categories.

[fn:5] Is this a trinitarian we? Or is this a royal we? It seems this is a tritarian because of [[file:Jn01.org][John's]] interpretation of the beginning
