
* Matthew 26
1. When Jesus had finished all these words, he said to his disciples, 
2. “You know that after two days the Passover is coming, and the Son of Man will be delivered up to be crucified.” 
3. Then the chief priests, the scribes, and the elders of the people were gathered together in the court of the high priest, who was called Caiaphas. 
4. They took counsel together that they might take Jesus by deceit and kill him. 
5. But they said, “Not during the feast, lest a riot occur among the people.” 
6. Now when Jesus was in Bethany, in the house of Simon the leper, 
7. a woman came to him having an alabaster jar of very expensive ointment, and she poured it on his head as he sat at the table. 
8. But when his disciples saw this, they were indignant, saying, “Why this waste? 
9. For this ointment might have been sold for much and given to the poor.” 
10. However, knowing this, Jesus said to them, “Why do you trouble the woman? She has done a good work for me. 
11. For you always have the poor with you, but you don’t always have me. 
12. For in pouring this ointment on my body, she did it to prepare me for burial. 
13. Most certainly I tell you, wherever this Good News is preached in the whole world, what this woman has done will also be spoken of as a memorial of her.” 
14. Then one of the twelve, who was called Judas Iscariot, went to the chief priests 
15. and said, “What are you willing to give me if I deliver him to you?” So they weighed out for him thirty pieces of silver. 
16. From that time he sought opportunity to betray him. 
17. Now on the first day of unleavened bread, the disciples came to Jesus, saying to him, “Where do you want us to prepare for you to eat the Passover?” 
18. He said, “Go into the city to a certain person, and tell him, ‘The Teacher says, “My time is at hand. I will keep the Passover at your house with my disciples.”’”
** The Lord's Supper
20. The disciples did as Jesus commanded them, and they prepared the Passover. 
21. Now when evening had come, he was reclining at the table with the twelve disciples. 
22. As they were eating, he said, “Most certainly I tell you that one of you will betray me.” 
23. They were exceedingly sorrowful, and each began to ask him, “It isn’t me, is it, Lord?” 
24. He answered, “He who dipped his hand with me in the dish will betray me. 
25. The Son of Man goes even as it is written of him, but woe to that man through whom the Son of Man is betrayed! It would be better for that man if he had not been born.” 
26. Judas, who betrayed him, answered, “It isn’t me, is it, Rabbi?” He said to him, “You said it.” 
27. As they were eating, Jesus took bread, gave thanks for it, and broke it. He gave to the disciples and said, “Take, eat; this is my body.” 
28. He took the cup, gave thanks, and gave to them, saying, “All of you drink it, 
29. for this is my blood of the new covenant, which is poured out for many for the remission of sins. 
30. But I tell you that I will not drink of this fruit of the vine from now on, until that day when I drink it anew with you in my Father’s Kingdom.” 
31. When they had sung a hymn, they went out to the Mount of Olives. 
** The Mount of Olives
32. Then Jesus said to them, “All of you will be made to stumble because of me tonight, for it is written, ‘I will strike the shepherd, and the sheep of the flock will be scattered.’ 
33. But after I am raised up, I will go before you into Galilee.” 
34. But Peter answered him, “Even if all will be made to stumble because of you, I will never be made to stumble.” 
35. Jesus said to him, “Most certainly I tell you that tonight, before the rooster crows, you will deny me three times.” 
36. Peter said to him, “Even if I must die with you, I will not deny you.” All of the disciples also said likewise. 
37. Then Jesus came with them to a place called Gethsemane, and said to his disciples, “Sit here, while I go there and pray.” 
38. He took with him Peter and the two sons of Zebedee, and began to be sorrowful and severely troubled. 
39. Then he said to them, “My soul is exceedingly sorrowful, even to death. Stay here and watch with me.” 
40. He went forward a little, fell on his face, and prayed, saying, “My Father, if it is possible, let this cup pass away from me; nevertheless, not what I desire, but what you desire.” 
41. He came to the disciples and found them sleeping, and said to Peter, “What, couldn’t you watch with me for one hour? 
42. Watch and pray, that you don’t enter into temptation. The spirit indeed is willing, but the flesh is weak.” 
43. Again, a second time he went away and prayed, saying, “My Father, if this cup can’t pass away from me unless I drink it, your desire be done.” 
44. He came again and found them sleeping, for their eyes were heavy. 
45. He left them again, went away, and prayed a third time, saying the same words. 
46. Then he came to his disciples and said to them, “Are you still sleeping and resting? Behold, the hour is at hand, and the Son of Man is betrayed into the hands of sinners. 
47. Arise, let’s be going. Behold, he who betrays me is at hand.”
** They Come for Jesus 
48. While he was still speaking, behold, Judas, one of the twelve, came, and with him a great multitude with swords and clubs, from the chief priests and elders of the people. 
49. Now he who betrayed him had given them a sign, saying, “Whoever I kiss, he is the one. Seize him.” 
50. Immediately he came to Jesus, and said, “Greetings, Rabbi!” and kissed him. 
51. Jesus said to him, “Friend, why are you here?” Then they came and laid hands on Jesus, and took him. 
52. Behold, one of those who were with Jesus stretched out his hand and drew his sword, and struck the servant of the high priest, and cut off his ear. 
53. Then Jesus said to him, “Put your sword back into its place, for all those who take the sword will die by the sword. 
54. Or do you think that I couldn’t ask my Father, and he would even now send me more than twelve legions of angels? 
55. How then would the Scriptures be fulfilled that it must be so?” 
56. In that hour Jesus said to the multitudes, “Have you come out as against a robber with swords and clubs to seize me? I sat daily in the temple teaching, and you didn’t arrest me. 
57. But all this has happened that the Scriptures of the prophets might be fulfilled.” Then all the disciples left him and fled. 
58. Those who had taken Jesus led him away to Caiaphas the high priest, where the scribes and the elders were gathered together. 
59. But Peter followed him from a distance to the court of the high priest, and entered in and sat with the officers, to see the end. 
60. Now the chief priests, the elders, and the whole council sought false testimony against Jesus, that they might put him to death, 
61. and they found none. Even though many false witnesses came forward, they found none. But at last two false witnesses came forward 
62. and said, “This man said, ‘I am able to destroy the temple of God, and to build it in three days.’” 
63. The high priest stood up and said to him, “Have you no answer? What is this that these testify against you?” 
64. But Jesus stayed silent. The high priest answered him, “I adjure you by the living God that you tell us whether you are the Christ, the Son of God.” 
65. Jesus said to him, “You have said so. Nevertheless, I tell you, after this you will see the Son of Man sitting at the right hand of Power, and coming on the clouds of the sky.” 
66. Then the high priest tore his clothing, saying, “He has spoken blasphemy! Why do we need any more witnesses? Behold, now you have heard his blasphemy. 
67. What do you think?” They answered, “He is worthy of death!” 
68. Then they spat in his face and beat him with their fists, and some slapped him, 
69. saying, “Prophesy to us, you Christ! Who hit you?” 
70. Now Peter was sitting outside in the court, and a maid came to him, saying, “You were also with Jesus, the Galilean!” 
71. But he denied it before them all, saying, “I don’t know what you are talking about.” 
72. When he had gone out onto the porch, someone else saw him and said to those who were there, “This man also was with Jesus of Nazareth.” 
73. Again he denied it with an oath, “I don’t know the man.” 
74. After a little while those who stood by came and said to Peter, “Surely you are also one of them, for your speech makes you known.” 
75. Then he began to curse and to swear, “I don’t know the man!” Immediately the rooster crowed. 
76. Peter remembered the word which Jesus had said to him, “Before the rooster crows, you will deny me three times.” Then he went out and wept bitterly. 
